kind: Service
apiVersion: v1
metadata:
  name: express
spec:
  type: LoadBalancer
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # Annotations for service
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"